# Generated by Django 5.2.7 on 2026-02-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Sigla de 2 o 3 letras (ej: IT, VEH)', max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Elemento')),
                ('status', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('AVERIADO', 'Averiado'), ('OBSOLETO', 'Obsoleto'), ('VENTA', 'Apto para venta'), ('DESCARTE', 'Apto para descarte')], default='FUNCIONAL', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.category')),
            ],
        ),
    ]
