# Generated by Django 5.2.7 on 2026-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('catalog', models.CharField(choices=[('IMPA', 'IMPA'), ('ISSA', 'ISSA')], default='IMPA', max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
